---
title: "Reading, managing and publishing papers"
author: "[Andreas Handel](https://www.andreashandel.com)"
date: "`r file.mtime(knitr::current_input())`"
output: 
  ioslides_presentation:
        self_contained: true
---

# Efficiently reading the literature


## Become an expert on a topic I

- If you know 'nothing', start with Wikipedia, CDC website, WHO, etc. Often information on those sites provide links to peer reviewed papers.
- Use Web of Science/Pubmed/Scopus/Google Scholar to find a highly cited review paper on the topic. 
- Look at all papers cited by the review. Skim through a few of the highly cited ones.
- Look at all papers that cite the review. Skim through a few of the highly cited ones.
- Mark/save/download papers that seem especially relevant. 


## Become an expert on a topic II

- Look at the most highly cited ones of those, see who cites them. Start reading full text artices.
- Find a few of the most influential/cited papers on the specific question you are interested in. 
- Look at titles/abstracts of every paper that cites those studies. Take a closer look at relevant papers.
- As you learn about a research area/topic, figure out who the main important people are. Search for their work. Read some/all of their papers.


## Remain up-to-date on a topic

- Follow specific journals, e.g. by subscribing to table of content emails.
- Follow specific topics, e.g. by setting alerts in places like ScienceDirect (Elsevier journals), Google alerts, PubMed.
- Follow specific individuals, e.g. by setting alerts in PubMed, Google Scholars.
- Participate in journal clubs.





# Efficiently managing your papers

## The basics
* Use a reference manager!
* Have a system!


## Reference Managers
* Good free ones (in my opinion) are Bibtex/Jabref.

* Non-free ones are Endnote, Papers, RefWorks.

* [Wikipedia has a comparison list](https://en.wikipedia.org/wiki/Comparison_of_reference_management_software)

* Check the features of different reference managers, figure out what works best for your workflow and setting. 

- Don't forget to include considerations of collaborative work into your decision.

- Pick one. Best to use only one system at a time.


## Paper full texts
* Some reference managers can link references to full text pdf. You might have to pay for storage. 
* You can add comments to pdfs through some reference managers.
* Use a system that lets you quickly find full text papers.
* Use constistent naming.
* Use a good folder system.
* Example: I use `firstauthorXXjournal - title.pdf` 



# Optimize your research impact

## Before you start your project

* Visualize the final product/paper
* Critically assess its expected quality
* Start thinking about suitable journals
* Decide and agree on authorship!

## While you do the research

* Start the manuscript draft early
* Write the background section as you do your literature review
* Add "skeletons" for each of your findings as sections
* Keep thinking about suitable journals
* Don't pay any attention to formatting


## When you are almost done

* Decide on the journal(s) you want to submit to
* Get input from others
* Finish writing your paper so it fits your target journal(s)
* Try to achieve fit with regard to content, mostly ignore formatting


## As you finish writing

* Make sure the message is clear.
* Try to put yourself in the shoes of the reader (and reviewer).
* Paper should be 'skimmable': A reader familiar with the topic should get the message by reading abstract and looking at figures and tables.
* Make each section as self-contained as possible (you might not know order of _Methods_ and _Results_).
* 1-2 main points/take-home messages a few side ones.
* Paper should have a single focus/topic, should be substantial but not sprawling.
* Everything that distracts from the main message should be left out or put in SM.

## Write for impact

- Spend a lot of time on the title
- Spend a good amout of time on abstract
- Contemplate how to get readers/citers
- Have a clear message/story


## How to choose the right journal

* Quality (for instance impact factor)
* Audience fit
* Speed (time to publication)
* Cost (open access or subscription-based)
* Other considerations (co-author wishes, special issue, etc.)


## Where to publish I

- Make sure it's a legitimate and not a fake/predatory journal.
  - If someone you don't know invites you to submit, it's most often not a good quality journal.
  - Check that the journal is indexed by 
  - Ask senior colleagues their opinion about a specific journal.

- Check impact factor/ranking or related metrics. Don't take those numbers too seriously, but use them to get a rough estimate of the quality of a journal.


## Where to publish II
- Consider fit.
- If you can, publish in an open access journal.
- I suggest to favor non-for profit publishers.
- Pay attention to journal policies, e.g. regarding conference presentations, pre-prints, data availability.


## How high to aim
* If you never get rejected, you are not optimizing impact.
* If you always get rejected 5+ times, you are wasting time/resources.
* Look at previous articles published in target journals, see if yours is likely similar (quality and type).
* Ask others who know the field to read the paper and suggest a journal (co-authors are good).
* You are likely not an impartial judge of your paper. At this stage you are either in love with or hate your project/paper.


## Finish and submit

* __If it's not published, it didn't happen!__
* Make sure everything is reviewer friendly (e.g. line numbers, figures and captions in text if possible).
* Spend as little time on formatting as possible.
* If you can suggest editors and reviewers, definitely do so.
* Write a good cover letter.
* Gather all other information and fill out all forms the journal requires. 


## When the reviews come back

* You can get anything from outright rejection without review to immediate acceptance (the latter is rare).
* Share reviews with your co-authors.
* Read reviews, especially negative ones, when you're in a state of mind where you can handle that.
* Let things sit for a few days before you start addressing reviewer comments.


## If your paper is rejected

* Rejection without useful feedback: immediately move to the next journal.
* Rejection with reviewer feedback: Go through it, address any useful comments. You might get the same reviewers again. 
* If the reviews are clearly ridiculous, you could appeal to the journal. Success likely depends on how clearly outrageous the reviews are and your status in the field (let the senior author do the appeal).
* Use the rejection feedback to help you decide where to send it next.


## If your paper is rejected

* Depending on how high you aim, expect to get rejected, possibly more than once.
* If you get rejected from your "safety journal", critically reassess your paper.
* Do not try to publish in a journal that does not meet your and your co-authors minimum standards of quality. Papers in bad journals will count negatively for your career/CV.

## If you are asked to revise

* Major revision: often sounds like a reject, so read the email carefully. 
* Read through reviewer comments. If you can address them or explain why you shouldn't, do the revision. If they ask for something you simply cannot do, decide if it's worth resubmitting or not. In that situation, it's okay to contact the editor. 

## If you are asked to revise

* Depending on how large the revisions are (and what software you use), use track changes.
* Write a document that lists every point raised by the reviewers and an explanation of how you addressed it.
* This is not the time or place to get into arguments! Thank the reviewers, acknowledge their comments, address everything you can, even if you think it doesn't make much of a difference. 
* If there's a point you can't or do not want to change, be as polite as possible in your refusal.

## If your paper is accepted

* Usually, either on the first try (happens rarely) or after revisions, you receive a _conditional_ acceptance. 
* The conditions are usually to make any small changes still requested by the reviewers and to make any formatting changes requested by the journal.
* At this stage, **and not earlier**, you need to follow all the journals formatting guidelines.
* This is also your last chance to make further edits. Go through the paper once more and send it to your co-authors for final feedback and approval.

## Timelines

* Time to publication can vary a lot between different fields and different journals.
* High-profile journals usually try for a quick turnaround.
* Journals like Science or Nature have full-time staff to make initial decisions usually within 24 hours.
* If your paper goes out for review, expect a few weeks to a few months for most good-quality biomedical journals.
* If you asked to do revisions you should do them on a similar timeframe of weeks or months.
* The duration of the whole process depends on the number of times you will need to resubmit before it's accepted.


## Useful considerations 

* Use a reference manager
* Make everything as automated as possible
* Pay attention to reproducibility
* Figure out one or two workflows that work for you and get really good at them


## Other thoughts

* Being a good writer/presenter might be even more important than being a good researcher!
* Work on all aspects of your writing/presentation (text, structure, grammar, style, figures, flow,...)!
* Read many other papers and as you do, don't only pay attention to content but also presentation to learn from good and bad examples.
* Read books on non-fiction writing.
* Most 'good writing' practices apply to all kinds of writing and presenting.






## Further Resources

- [The RoMEO service](http://sherpa.ac.uk/romeo/index.php) provides information regarding pre-print (and other) policies of different journals.

