---
title: Creating a website in less than 1 hour - part 1
subtitle: Part 1 - blogdown, Hugo and Netlify
author: Andreas Handel
date: '2019-01-03'
slug: blogdown-website
draft: true
categories: []
tags: []
summary: ''
lastmod: '2020-01-03'
featured: no
disable_jquery: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


```{r, include = FALSE}
#remotes::install_github('emo')
#library('emo')
```

The following are step-by-step instructions for creating your own website using [blogdown](https://bookdown.org/yihui/blogdown/), [Hugo](https://gohugo.io/) and [Netlify](https://www.netlify.com/).

In [part 2](), you will learn how to add [GitHub](https://GitHub.com) to your workflow to make things even more automated and efficient.


# Required skills

I assume that you have general computer literacy, but no experience with any of the tools that will be used. Also, no coding, web-development or related experience is expected. 

# What this document covers

This document is meant to provide you with the minimum required instructions to get your own website up and running quickly. As such, instructions and background information are kept at a minimum. I used a _recipe-like_ approach by giving hopefully detailed and specific enough instructions to get things to work. I'm not covering any _why_ here or provide much further explanations. If you decide you like to use this setup for your website, you will likely want to go beyond this document and learn a bit more about the various tools involved in the process. To that end, links to further resources are provided. Those resources also discuss a bit why you would want this setup versus something like e.g. Wordpress. 

# Who this is (not) for

**This way of making and hosting a website might be for you if:**

* You are (or would like to be) an R, RMarkdown and GitHub user. This is a method of creating a website that very efficiently fits into your workflow. 
* You want a way to host a website where all the content is fully controlled by you, and the website can be hosted without much resources (and for free). 
* You are curious about R/RMarkdown/GitHub, how to use it to build a website, and you've got a bit of time to spare and want to give it a try.

**This way of making and hosting a website might not be for you if:**

* Your workflow is MS Word, Powerpoint, etc. and you are not interested in R/Markdown/GitHub.
* You want everything accessible through a graphical interface.



# Motivating Examples

If you want to see a few nice examples of websites written with blogdown/Hugo, check these out:

* [Allison Hill](https://alison.rbind.io/)
* [Amber Thomas](https://amber.rbind.io/)
* [TSL Laboratory](https://www.tslab.org/)
* [Flip Tanedo](https://theory.ucr.edu/flip/)

I picked them pretty much randomly, based on the fact that their sites looked nice. Tons more of examples exist. See e.g. [here](https://awesome-blogdown.com/) or [here](https://sourcethemes.com/academic/#expo).



# Quick tool overview

A few different software tools are working together for this website built. **In most cases, they play nicely together and you don't need to worry about details!** But it is still good to know the names of the different components.

**[R](https://www.r-project.org/)** and **[RStudio](https://rstudio.com/products/rstudio/download/)** we won't really use those for their normal purpose as statistics/coding software/platform, but since blogdown is part of the RMarkdown family of packages, we need to use R and RStudio to access blogdown.

**[blogdown](https://bookdown.org/yihui/blogdown/)** is an R package that interfaces with Hugo and allows you to create websites easily using RMarkdown syntax. 

**[Hugo](https://gohugo.io/)** is software that operates in the background. It takes all the content you create for your website (your text, your pictures, etc.), applies layout to your site based on a chosen theme, and turns everything into files that can be placed on Netlify and read by anyone's web browser. You will likely not have to think or learn much about Hugo, at least not initially.

**[Netlify](https://www.netlify.com/)** is the service we'll use to host the website. It offers a free plan, which is great for a starter website (you can always upgrade once you become famous and everyone visits your website. 
Netlify is very easy to set up and use, and it can automatically pull information from GitHub to build your site every time you update it (see part 2 for this). 

While Netlify and RStudio have paid options, for our purpose we can use their free versions. Hugo, blogdown and R are completely free.


# Pre-requisites

First, you need to set up accounts and install some software for the tools we will be using. 


## Get a Netlify account

Go to [the Netlify website](https://www.netlify.com/) and sign up for an account. Follow the sign-up steps to set up your account.


## Install R and RStudio 
If you don't already have it on your computer, [install R first](https://www.r-project.org/). You can pick any mirror you like. If you already have R installed, make sure it is a fairly recent version. If yours is old, I suggest you update (install a new R version).

Once you have R installed, install the free version of [RStudio Desktop](https://www.rstudio.com/products/rstudio/download/). Again, make sure it's a recent version. If you have an older verion of RStudio, you should update.

Installing R and RStudio should be fairly straightforward. If you want some more details or need instructions, see [this page](https://andreashandel.GitHub.io/MADAcourse/1c_RandRStudio.html) (which is part of an online course I teach).


# Setting up the website 

With the above registration and installation bits out of the way, you can get started at creating your website. To do so, follow these steps:

* Open RStudio. Install the blogdown package by typing `install.packages('blogdown')` in the R console (the lower left window in RStudio). Note that all `R` commands are case sensitive. You need to be online for this to work. You should see `blogdown` and several other packages be installed.
* Load `blogdown` by typing `library(blogdown)` into the R console (this step you need to do every time you open/re-load R/RStudio). 
* Under `File`, choose `New Project`, `New Directory`, `Website using blogdown`. On the following screen, specify a meaningful directory name (e.g. YOURNAMEWEBSITE), place it somewhere on your computer, check all boxes (apart from 'open in new session'), and write `gcushen/hugo-academic` into the Hugo theme box. Then click `Create Project`.

This creates a new website and installs and sets up the chosen theme, complete with a small sample site. Be patient, it might take some time. As long as you see a little red stop sign in the top left corner of the R Console window, you know things are still running. Once everyting is done, a file called `config.toml` will likely pop up. Ignore for now. You will see a lot of new files have shown up in your project/repository folder. 

* The command above installed a small example site. We can look at it by asking RStudio/blogdown to _serve_ the site by typing `serve_site()` into the R console. You might get a warning message, but hopefully things work and the bottom right window, which is the RStudio viewer, shows a website. Click on the symbol next to the broom in the top left corner of that window to see the website in your browser. This is your new site. Now it's time to customize and create content.


## A word about themes

All modern websites follow the concept of splitting content from layout and only merging them at some point in the process of building a website. All the formatting that gives a site a specific layout is often called a `Theme`. The theme determines the look of your website. Hugo has a lot and quickly growing [number of themes](https://themes.gohugo.io/) (though not as many as Wordpress). The idea is that you can switch themes and thus layout without too much difficulty. In practice, there is still often a good bit of adjustment needed when you go from one theme to another. Thus, it is worth spending some time deciding on a theme before you go "all in". The `Academic` theme we use here is currently one of the most popular ones for Hugo. It has a lot of features. The drawback of that is that it's fairly complex. I was considering choosing a simpler theme, but I figured to illustrate what's possible, and because it's widely used and under active development, we'll go with this theme. You can explore different themes later. 



# A brief explanation of your new website

The previous steps have given you a website with some example starter content. Any complex website has a certain structure consisting of folders and files. These files and folders either live only on a website server and you never see them (e.g. Wordpress), or they exist locally, as is the case for Hugo (and similar such website generators, e.g. `Jekyll`.)

Some of the files and folders you do not need to care much about, others you will need to intereact with. To get a bit of an idea what lives where, here is a quick overview. Some of this depends on the Hugo theme you are using, but most of them have a rather similar structure.

* The folder `config` contains files that control some of the overall website look and feel. We'll visit them later. In Hugo, those files that control configuration are called either `TOML` or `YAML` files. Many files have both bits of TOML/YAML and other content in them, as you will see below.
* The folder `content` and its subfolders contain almost all the actual content for your website. We'll edit some of that soon.
* The folder `public` is the one that contains your finished website once Hugo has processed your content and applied the layout from your chosen theme. That folder is the one which is deployed to a webserver. As you will see below, for our setup all this happens automatically, so you never really have to care about this folder much.
* The folder `static` contains subfolders where you can store images and other media (e.g. pdf files or video/audio, etc) that you want to be part of your site.
* The folder `themes` includes the different Hugo themes you installed. You can have several themes installed and switch between the one you want by editing the configuration files. Note however that themes differ in their details of how they do things, so it is a good idea to check out a few themes first, then settle on one and build your website _for real_ once you picked one.
* The other folders that might exist are ones you don't need to worry about, at least not initially. Some of those folders can contain your own formatting and layout choices overwriting the main theme. We won't discuss them here but once you really want to start configuring your site, those will become important. 



# Edit existing content

Now that you know a little bit how your website is structured, let's dig in and add and modify it. We'll start with some modifications, followed by creating new content.

All (or at least most) content goes into the `content` folder and its subfolders. Content is generally written in (R)Markdown. Markdown is very easy to learn. If you are not familiar with it, check out [this nice interactive tutorial](https://www.markdowntutorial.com/) or this [cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet). See e.g. the RMarkdown section on [this page](https://andreashandel.github.io/MADAcourse/1e_ToolsforReproducibility.html) for a bit more information and further links to resources. We'll take it slow and I'll guide you through it.

The Academic theme, and many other modern websites, use a layout that employs `widgets`, which are components of a site that are individually formatted and styled. On the demo site you just created, you see many different sections, each is a widget. Which widgets you want is controlled by files in the `/content/home/` folder. Go into that folder (from within RStudio) and open the `demo.md` file. You will see a bunch of text. Some commands are between `+++` signs, this is called the TOML (or YAML if it's 3 `---`) header. These are instructions for the layout. The text below is what is actually shown on the site.

As you stare at the content of the file, you might recognize that it corresponds to the 2nd block of the demo website with the dark bubble content. Let's say you don't want this particular widget on your home page. The easiest way is to set `active = false`. (You can also delete the whole file if you are sure you don't want it). Do that. You should notice 2 things. In the bottom-left RStudio window (the R console) you should see a bit of code showing that the website was re-built and updated in real time. If you re-load the page in your browser, the widget and its content should be gone. You can try turning off other sections of the main page using this approach.

Now let's open the `about.md` file. You will notice that it doesn't really contain any content. Instead, it pulls the content from another location, namely the specified file in the `authors` folder. Go into `/content/authors/admin/` and open the `_index.md` file. There you see the content that is displayed on the main page. Modify it as you like.



At the top of your new website, you find a navigation bar, one of the entries is `About`. Click on it. Now let's find the file that produces that page and edit it. To that end, go to the `Files` tab in the lower right RStudio window and browse to `content -> about` folder, click on `_index.md`. You'll note that the text in that file corresponds to what you see on the website. You also see an example of how links are written in Markdown.

Replace the text in that file. Change the date and title in the top section between the 3 `---` symbols (that section is called the YAML header. Somewhat confusingly, Hugo also sometimes uses similar sections between 3 `+++` signs, at which point it is called a TOML header. Don't ask me...). Set the date for today, the title to `About YOURNAME`. Once you save the file, you'll see that something is running in the R console, and if you look at the website, things have been updated. You can see your edits in almost real time!

Now replace the rest of the document with whatever you like. Try to include a link to something, and use a few headings. You can try to include further Markdown elements as described in the above mentioned resources. We'll get to things like including pictures below.

Let's edit more content. On the left side, under "Recent Posts", find the one called "Getting Started with Hugo" and click on it. Note in the URL bar that the name of the page is called `hugoisforlovers`. Let's try and find the text that goes with that blog post. To that end, go to the `content -> blog` folder. You find there a file called `hugoisforlovers.md` (there are also files that seem to be for different languages, we can ignore those). Open the file. You'll see the content that corresponds to the website.


# Create new content



# Change site settings



# More Information

* A short introductory course is Allison Hill's [summer of blogdown](https://alison.rbind.io/project/summer-of-blogdown/).
* A lot of details and further information can be found in [the blogdown book](https://bookdown.org/yihui/blogdown/).
https://alison.rbind.io/post/2017-06-12-up-and-running-with-blogdown/
https://www.williamrchase.com/post/2019/10/28/making-my-personal-website/





