---
title: "Reading, managing and publishing papers"
author: "[Andreas Handel](https://www.andreashandel.com)"
date: "`r file.mtime(knitr::current_input())`"
output: 
  ioslides_presentation:
        self_contained: true
---

# Efficiently reading the literature


## Become an expert on a topic 

* Becoming a real expert does of course take time and active engagement with a topic.
* With good (re)search skills, it is fairly easy to become an almost-expert in many topics, especially those where you have a good foundation.
* If you know 'nothing', start with Wikipedia or other general trustworthy websites. Often information on those sites provide links to peer reviewed papers.
* Next use Web of Science/Pubmed/Scopus/Google Scholar to find a highly cited review paper on the topic. Read it.


## Efficient literature scanning 

* Start with the highly cited review you found previously, or another relevant paper.
* Look at all papers cited by the starting article. Check titles/abstracts of those references, focus on highly cited ones.
* Look at all papers that cite the starting article. Check titles/abstracts, focus on highly cited ones.
* Continue this pattern (look who is cited and who cites) for other relevant articles.

## Becoming an expert 

* Start reading some of the relevant and influential papers you found in your previous search.
* Identify a few important and influential papers that are close to the specific question you are interested in. 
* Look at titles/abstracts of every paper that cites those studies. Take a closer look at relevant papers.
* As you learn about a research area/topic, figure out who the main important people are. Focus initially on a few names. Search for their work. Read some of their papers.


## Remain up-to-date on a topic

* Follow relevant journals, e.g. by subscribing to table of content emails.
* Follow specific topics, e.g. by setting keyword alerts (e.g. _Influenza_) in places like ScienceDirect (Elsevier journals), Google alerts, PubMed.
* Follow specific individuals, e.g. by setting alerts in PubMed, Google Scholars, or by following people on Twitter.
* Participate in journal clubs.



# Efficiently managing your papers

## The basics
* Use a reference manager!
* Have a system!


## Reference Managers
* Good free ones (in my opinion) are Zotero and Jabref.

* Non-free ones are Endnote, Papers, RefWorks.

* [Wikipedia has a comparison list.](https://en.wikipedia.org/wiki/Comparison_of_reference_management_software)

* Check the features of different reference managers, figure out what works best for your workflow and setting. 

* Don't forget to include considerations of collaborative work into your decision.

* Pick one. Best to use only one system at a time. Sometimes collaborations require flexibility.


## Full text management
* Some reference managers can link references to full text pdf. You might have to pay for storage. 
* You can add comments to pdfs through some reference managers.
* Use a system that lets you quickly find full text papers.
* Download papers liberally so you can get to them even if you are not online/have university access.

## Full text management
* Use consistent naming.
  * Example: I use `firstauthorXXjournal - title.pdf` 
* Use a good folder system.
  * Example: I sort by pathogen, then by model/data/review.
* Have some good software that can quickly search your computer.
  * Example: I'm on Windows and I use [Everything.](https://www.voidtools.com/downloads/)



# Tips for successful paper writing and publishing 


## Before you start your project

* Visualize the final product/paper.
* Critically assess its expected quality.
* Start thinking about suitable journals.
* Decide and agree on authorship!

## While you do the research

* Start the manuscript draft early.
* Write the background section as you do your literature review. (Could eventually become a [full review article.](https://doi.org/10.1371/journal.pcbi.1003149) )
* Add "skeletons" for each of your findings as sections.
* Keep thinking about suitable journals.
* Don't pay any attention to formatting.


## Once your are mostly done with the research
* Assess scope. A paper should have a single focus/topic, should be substantial but not sprawling.
* 1-2 main points/take-home messages (maybe a few side points). If you have more, consider splitting it into 2 papers.
* Everything that distracts from the main message should be left out or put in SM.

## As you finish writing
* Make sure the message is clear.
* Try to put yourself in the position of the reader (and reviewer).
* A paper should be 'skimmable': A reader familiar with the topic should get the message by reading abstract and looking at figures and tables.
* Make each section as self-contained as possible (you might not know order of _Methods_ and _Results_).
* [Ten simple rules for structuring papers.](https://doi.org/10.1371/journal.pcbi.1005619)


## When you are almost done

* Decide on the journal(s) you want to submit to.
* Get input from others.
* Finish writing your paper so it fits your target journal(s) audience.
* Mostly ignore formatting.




## Tips to increase visibility 

* Spend a lot of time on the title.
* Spend a good amout of time on abstract.
* Contemplate how to get readers/citers.
* Have a clear message/story.


## How to choose the right journal
* Quality (for instance impact factor). Don't take any one metric too seriously, but use them to get a rough estimate of the quality of a journal.
* [Make sure it's not a fake/predatory journal](https://www.jabfm.org/content/31/5/671).
  * If someone you don't know invites you to submit, it's most often not a good quality journal.
  * Check that the journal is indexed by PubMed, Web of Science. No guarantee either way, but a good check.
* Ask senior colleagues for their opinion about a specific journal.


## How to choose the right journal
* Audience fit
* Speed (time to publication)
* Cost and Reach (open access or subscription-based)
* Type, e.g. society/non-profit or for-profit
* Journal policies, e.g. regarding conference presentations, pre-prints, data availability.
* Other considerations (co-author wishes, special issue, etc.)


## How high to aim
* If you never get rejected, you are probably not optimizing impact.
* If you always get rejected 5+ times, you are wasting time/resources.
* Look at previous articles published in target journals, see if yours is likely similar (quality and type).
* Ask others who know the field to read the paper and suggest a journal (co-authors are good).
* You are likely not an impartial judge of your paper. At this stage you are either in love with or hate your project/paper.


## Finish and submit

* __If it's not published, it didn't happen!__
* Make sure everything is reviewer friendly (e.g. line numbers, figures and captions in text if possible).
* Spend as little time on formatting as possible. More and more journals allow the 1st submission to be in any _reasonable_ format.
* If you can suggest editors and reviewers, definitely do so.
* [Write a good cover letter.](https://www.nature.com/articles/ni0208-107)
* Gather all other information and fill out all forms the journal requires. 


## When the reviews come back

* You can get anything from outright rejection without review to immediate acceptance (the latter is rare).
* Share reviews with your co-authors. In general, as courtesy, keep co-authors updated, even if you don't require their input.
* Read reviews, especially negative ones, when you're in a state of mind where you can handle that.
* Let things sit for a few days before you start addressing reviewer comments.


## If your paper is rejected

* Rejection without useful feedback (e.g. editorial rejection): immediately move to the next journal.
* Rejection with reviewer feedback: Go through it, address any useful comments. You might get the same reviewers again at a different journal. 
* If the reviews are clearly ridiculous, you could appeal to the journal. Success likely depends on how outrageous the reviews are, the fanciness of the journal and your status in the field (let the senior author do the appeal).
* Use the rejection feedback to help you decide where to send it next.


## If your paper is rejected

* Depending on how high you aim, expect to get rejected, possibly more than once.
* If you get rejected from your "safety journal", critically reassess your paper.
* Do not try to publish in a journal that does not meet your and your co-authors minimum standards of quality. Papers in bad journals will count negatively for your career/CV.

## [If you are asked to revise](http://www.stgries.info/research/ToEditors.pdf)

* Major revision: Is often worded to sound like a reject, so read the email carefully, ask a senior co-author. 
* Read through reviewer comments. If you can address them or explain why you shouldn't, do the revision. If they ask for something you simply cannot do, decide if it's worth resubmitting or not. In that situation, it's okay to contact the editor and ask for guidance. 

## If you are asked to revise

* Depending on how large the revisions are (and what software you use), use track changes.
* Write a document that lists every point raised by the reviewers and an explanation of how you addressed it.
* This is not the time or place to get into arguments! Thank the reviewers, acknowledge their comments, address everything you can, even if you think it doesn't make much of a difference. 
* If there's a point you can't or do not want to change, be as polite as possible in your refusal.
* [Ten simple rules for writing a response to reviewers.](https://doi.org/10.1371/journal.pcbi.1005730)

## Suggestions for replies to reviewer comments

* "We thank the reviewer for their comment. We did what they asked for." 
* "We thank the reviewer for their comment. We weren't quite able to do Z, but we did X and Y to show that Z is likely not a problem. We added all that additional analysis into the main text/SM." 
* "We thank the reviewer for their comment. We agree our study has limitation Y. We now discuss this more explicitly in section X." 


## If your paper is accepted

* Usually, either on the first try (happens rarely) or after revisions, you receive a _conditional_ acceptance. 
* The conditions are usually to make any small changes still requested by the reviewers and to make any formatting changes requested by the journal.
* At this stage, **and not earlier**, you need to follow all the journals formatting guidelines.
* This is also your last chance to make further (minor) edits. Go through the paper once more and send it to your co-authors for final feedback and approval.

## Timelines

* Time to publication can vary a lot between different fields and different journals.
* High-profile journals usually try for a quick turnaround.
* Journals like Science or Nature have full-time staff to make initial decisions usually within 24 hours.
* If your paper goes out for review, expect a few weeks to a few months for most good-quality biomedical journals.
* If you asked to do revisions you should do them on a similar timeframe of weeks or months.
* The duration of the whole process depends on the number of times you will need to resubmit before it's accepted.

## Some publishing tips
* Understand there is luck involved.
* Fancy journals are much more worried to accept a paper that's not that great (i.e. highly citeable) than to reject a great one.
* If you have the option to be a reviewer, take it. It's a good learning experience.
* As long as you did good work, you'll be able to publish it somewhere eventually.
* [Ten Simple Rules for Getting Published](https://doi.org/10.1371/journal.pcbi.0010057)


## General writing tips 
* Work on all aspects of your writing/presentation (text, structure, grammar, style, figures, flow,...).
* Read many papers and as you do, not only pay attention to content but also presentation to learn from good and bad examples.
* Read books on non-fiction writing.
* Most 'good writing' practices apply to all kinds of writing and presenting.
* [Ten simple rules for scientists: Improving your writing productivity](https://doi.org/10.1371/journal.pcbi.1006379)


## General thoughts

* Being able to (re)search the literature, organize information (references) and write a clear report (paper) are incredibly valuable skills beyond academia! Practice them and be aware that you are acquiring those valuable skills.

* Being a good writer/presenter might be even more important for general career advancement (especially outside academia) than being a good researcher.


## Further Resources

* [Ten Simple (Empirical) Rules for Writing Science](https://doi.org/10.1371/journal.pcbi.1004205)
* [Ten Simple Rules for Writing Research Papers](https://doi.org/10.1371/journal.pcbi.1003453)
* [Successful Scientific Writing and Publishing: A Step-by-Step Approach](https://www.cdc.gov/pcd/issues/2018/18_0085.htm)
* [The RoMEO service](http://sherpa.ac.uk/romeo/index.php) provides information regarding pre-print (and other) policies of different journals.

